### ISSUE TITLE
The error messages in lgsvl simulator with Autoware.

### ISSUE THREAD

**Issue by oiz5201618** [lgsvl/simulator#58]
Hi, thanks in advance for any reply.
If this issue is not suitable for this repository, please inform and close it, thanks!

When I try to run Autoware with lgsvl_simulator, it occur some error as below.
My Autoware runs with kinetic version in the docker container and all installations exactly follow the guide.

1. The **Localization** doesn't display the time at the right of "Ref", and the error message repeatedly shows up `Failed to find match for field 'intensity'.`
![image](https://user-images.githubusercontent.com/16171772/50570879-970ec200-0dd6-11e9-9f8c-5421470bf5ef.png)

2. Next, the **Detection** also repeatedly warns `[ INFO] [1546326933.338934217]: wayarea layer not contained in the OccupancyGrid`, but this is only the **INFO** message.
I'm not sure whether this message affects the system or not.
![image](https://user-images.githubusercontent.com/16171772/50570944-2a94c280-0dd8-11e9-9483-bf15265d6c25.png)

3. Final, once the **Motion Planning** launches, the `config_waypoint_follower_rostopic-6` process has died.
![image](https://user-images.githubusercontent.com/16171772/50571008-c115b380-0dd9-11e9-828c-3a197f2d7146.png)

After these three error messages, my Autoware still can operate the sensor fusing in **Detection** and plan the path in **Mission Planning**, but the vehicle just stucks.

![image](https://user-images.githubusercontent.com/16171772/50571044-64ff5f00-0dda-11e9-8903-b960d6fcdf42.png)

**Comment by hadiTab** [comment]
@oiz5201618 it seems like you have autoware setup pretty well with the simulator. I've addressed the issues bellow.

1. This is related to the PCL library not expecting to see an intensity field in the pointcloud map I believe. It should not affect anything.

2. This one should also have no effect. As far as I can recall it is Autoware detection tries to match the obstacles to the wayarea (the drive-able areas) and it is failing to do so because the HD map does not contain that information. It is an optional functionality though and detection should work without it.

3. Unfortunately, I am not entirely sure what the reason for this one is. It happens sometimes for me as well. It sometimes happens on some computers when the waypoint follower node is launched through the launch file (the node is dying immediately after being launched). It does not happen when the node is launched manually. To launch it manually follow these steps:
- Switch over to the 'Computing' tab in the runtime manager.
- Scroll down and find 'pure_pursuit' and 'twist_filter' in the right side column (probably under the title waypoint follower) and check the box in front of both of them.
- The car will likely start moving now. The motion may not be smooth though. You can tweek the motion parameters by clicking on the button to the right of 'pure_pursuit' and changing the configuration parameters.

Let me know if this helps.

**Comment by oiz5201618** [comment]
@hadiTab thanks for your detailed reply.
The manual launch can avoid the process died problem, but the vehicle still stucks.

And I encountered another problem as below.
* My sensor fusing just keeps rotating in rviz, but no error messages show up.
---
![image](https://user-images.githubusercontent.com/16171772/50672248-f0166a00-1011-11e9-9aab-30f6b3e63df3.png)
---
![image](https://user-images.githubusercontent.com/16171772/50672298-3075e800-1012-11e9-8f1f-75f7b298c0c6.png)
---
![image](https://user-images.githubusercontent.com/16171772/50672306-3e2b6d80-1012-11e9-864c-00b7e7d96b3f.png)
---

The following is my device infomation. Is my computing power not enough?
* CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz with 4 cores 8 threads.
* RAM: 16GB
* GPU: GeForce GTX 1060 6GB

**Comment by oiz5201618** [comment]
@hadiTab 
I solved the sensor data rotating problem by restarting my simulator, it seems some configuration went wrong, but the vehicle still cannot move.

![image](https://user-images.githubusercontent.com/16171772/50678839-92971300-103b-11e9-8128-249137ee46d7.png)

When I open rviz, the error message shows up.
![image](https://user-images.githubusercontent.com/16171772/50678857-acd0f100-103b-11e9-8f3b-15d2e5c0467a.png)

**Comment by hadiTab** [comment]
@oiz5201618 I'm not sure why you are seeing that error, but it should not affect the vehicle moving. It seems like some of the message definitions in Autoware have changed and do not match what rviz is expecting, but that would only affect the rviz visualization.

Try the following:
1. Launch everything, switch over to the 'Computing' tab and launch pure_pursuit and twist_filter.
2. Open the settings menu for pure_pursuit and switch the mode to 'dialog'.
3. Increase the speed to about 15 and the lookahead distance to about 5. If the vehicle does not move try tuning these two variables. The effect should be immediate, i.e. as you move the slider the variables are changed instantaneously and you do not need to click OK for it to take affect. Play with these two variables until the vehicle starts to move.

**Comment by oiz5201618** [comment]
If I send the control command by `rostopic pub`, the vehicle moves.
`$ rostopic pub /twist_cmd geometry_msgs/TwistStamped ${Arg}`

But if I give the goal by the same method, the vehicle still stucks.
`$ rostopic pub /move_base_simple/goal geometry_msgs/PoseStamped ${Arg}`

It seems the motion_planner doesn't work properly.

**Comment by oiz5201618** [comment]
Hi, @hadiTab 
Thank you very much for your kindly reply.

I solved the problem by enabling the **astar_planner** function in the 'Computing' tab, which is also launched in the `my_motion_planning.launch` file. In fact, we also can switch the motion planner to the other one (e.g. lattice_planner), the vehicle will move properly.

![image](https://user-images.githubusercontent.com/16171772/50828543-a4025700-137c-11e9-9d79-988b1dd58f92.png)

So the problem is that **astar/lattice_planner** which provides a reference path for **pure_persuit** dosen't be launched, and I think I misunderstood the steps you mentioned.

But if I enable traffic in the Unity, the vehicle collides with the vehicles ahead instead of avoiding or stoping. It seems the avoidance function doesn't work despite I enable it in the astar_planner.

![image](https://user-images.githubusercontent.com/16171772/50828534-9f3da300-137c-11e9-85a6-9c3a073638b5.png)
